version: "3.8"

services:
  app:
    container_name: milk-run-uat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    env_file:
      - .env
    restart: always
